<robot name="scout_mini" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="base_width" value="0.580"/>
  <xacro:property name="base_length" value="0.612"/>
  <xacro:property name="base_height" value="0.245"/>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}"/>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}"/>
    </collision>
  </link>

  <link name="rslidar">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.1"/>
      </geometry>
      <origin xyz="0 0 0.2"/>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.1"/>
      </geometry>
      <origin xyz="0 0 0.2"/>
    </collision>
  </link>

  <joint name="base_to_rslidar" type="fixed">
    <parent link="base_link"/>
    <child link="rslidar"/>
    <origin xyz="0 0 ${base_height}"/>
  </joint>

</robot>
